services:
   server:
      container_name: restaurant-management-server
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '5002:5002'
      restart: always
      env_file:
         - .env
      volumes:
         - .:/app
         - /app/node_modules
      networks:
         - restaurant-management-network

   nginx:
      container_name: restaurant-management-nginx
      image: nginx:alpine
      ports:
         - '80:80'
         - '443:443'
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
         - ./nginx/certs:/etc/ssl/certs:ro
      depends_on:
         - server
      networks:
         - restaurant-management-network

networks:
   restaurant-management-network:
      driver: bridge
