version: '3.9'

services:
  server:
    image: jasimihsan9656/restaurant-backend:latest   # pull from Docker Hub instead of building locally
    container_name: restaurant-management-server
    platform: linux/amd64
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "5002:5002"
    networks:
      - restaurant-management-network

  nginx:
    image: nginx:alpine
    container_name: restaurant-management-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/mentorshub.ddns.net/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/mentorshub.ddns.net/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - server
    networks:
      - restaurant-management-network

networks:
  restaurant-management-network:
    driver: bridge
